### ISSUE TITLE
Website vulnerability: UFU on php upload 

### ISSUE THREAD

**Issue by diegomariani** [davcri/Unibox-Ajax#6]
**Unrestricted File Upload**
Unrestricted File Upload vulnerability found when upload a resource file. Just uploading a php shell to gain entirely control over the server file system.
Where => https://github.com/davcri/Unibox-Ajax/blob/master/Classes/Control/Upload.php#L136-L193
How to => http://stackoverflow.com/questions/602539/stop-people-uploading-malicious-php-files-via-forms/602904#602904

**Comment by davcri** [comment]
Thank you very much for opening the issue and for the links !

**Comment by diegomariani** [comment]
Don't mention it ! Unrestricted is one of the most commonly bugs in php development.
There are several steps to achieve application security
- File name extension verification
- Content type verification
- File Content verification
http://resources.infosecinstitute.com/file-upload-vulnerabilities/
Anyway you did a very good work, better that others that I seen. Keep up the good work

Cheers

DM
