### ISSUE TITLE
Add class autoloading and PSR standards

### ISSUE THREAD

**Issue by diegomariani** [davcri/Unibox-Ajax#7]
Using class autoloading could be a very nice improvement on your code. Setting up autoloading is very easy https://thomashunter.name/blog/simple-php-namespace-friendly-autoloader-class/
If you want to enhance your project quality, you can introduce PSR PHP standard http://www.php-fig.org/

cheers

**Comment by davcri** [comment]
PSR is very useful, I wish I had discovered it before starting the project. Unfortunately this project was our first attempt on a web application and we didn't follow any PSR or best practices, just common sense. What we have now is a lot of code that should be reviewed and this can take time.

**Comment by diegomariani** [comment]
Don't worries. it was just a suggestion, that's a good job. Anyway, keep up the good work.
Have a nice one
